name = "gh-cmx"
compatibility_date = "2025-01-11"
pages_build_output_dir = ".next"

[env.production.vars]
ENVIRONMENT = "production"
GITHUB_OWNER = "erolledph"
GITHUB_REPO = "gh-cmx"
ADMIN_PASSWORD = "admin123"
NEXT_PUBLIC_SITE_URL = "https://b640c8c4.gh-cmx.pages.dev"
NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyC4xLkBv4DjVGF1JYjWKxxqDDqqGhCDxzU"
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "gh-cmx.firebaseapp.com"
NEXT_PUBLIC_FIREBASE_PROJECT_ID = "gh-cmx"
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "gh-cmx.appspot.com"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "726556325024"
NEXT_PUBLIC_FIREBASE_APP_ID = "1:726556325024:web:bfb9c20eaffe6d2d0b5e00"




