name = "aitech-insis"
compatibility_date = "2025-01-11"
pages_build_output_dir = ".next"

compatibility_flags = ["nodejs_compat"]

[env.production.vars]
GITHUB_OWNER = "myUsername"
GITHUB_REPO = "repo name"
NEXT_PUBLIC_SITE_URL = "https://mydomain.com"
